#!/bin/bash

#chkconfig: 345 80 20

JBOSS_HOME = '/opt/jboss/jboss-as-7.1.1.Final/'

start(){
	echo "Starting Jboss"
	/opt/jboss/jboss-as-7.1.1.Final/bin/standalone.sh -c standalone-ha.xml > /home/user/jboss_log.txt &
}
stop(){
    jboss_running="$( ps -ef | grep $JBOSS_HOME | grep -v 'grep' )"
    if [ -z "${jboss_running}" ] ; then
	echo "JBoss is not running"
    else
	echo "Stopping JBoss AS 7.1.1"
        cd ${JBOSS_HOME}/bin
	sh ./jboss-cli.sh --connect command=:shutdown
	echo "Checking for any remaining processes"
	sleep 5
	jboss_pids=$(ps -ef | grep java | grep -v grep | awk '{ printf $2" " }')
	# if there are remaining processes, kill them
	if [ ! -z "$jboss_pids" ] ; then
	    kill -9 $jboss_pids
	fi
	echo "No remaining processes. Jboss stopped"
    fi	
}

restart(){
	stop
	sleep 15
	start
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        stop
	sleep 5
	start
    ;;
    *)
        echo "Usage: /etc/init.d/jboss {start|stop|restart}"
        exit 1
    ;;
esac

exit 0
