default['jboss']['jboss_home'] = "/opt/jboss" 
default['jboss']['url'] = "http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip" 
default['jboss']['name'] = "jboss-as-7.1.1.Final"
default['httpd']['mod_jk']['url'] = "http://www.eu.apache.org/dist/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.40-src.tar.gz"
default['httpd']['mod_jk']['name'] = "tomcat-connectors-1.2.40-src"
